# Generated by Django 2.2.16 on 2022-08-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220826_1649'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Titles',
            new_name='Title',
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('title',), 'verbose_name': 'Отзыв. model Review', 'verbose_name_plural': 'Отзывы. model Review'},
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='title_one_review'),
        ),
    ]
